name: Trigger auto deployment for container-app-oij5j3q5bw4f6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-oij5j3q5bw4f6-AutoDeployTrigger-b2f17937-a81d-40f4-abce-bbc9ca864f94.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPOIJ5J3Q5BW4F6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPOIJ5J3Q5BW4F6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPOIJ5J3Q5BW4F6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPOIJ5J3Q5BW4F6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPOIJ5J3Q5BW4F6_REGISTRY_PASSWORD }}
          containerAppName: container-app-oij5j3q5bw4f6
          resourceGroup: appspacesragappa2b09358
          imageToBuild: default/container-app-oij5j3q5bw4f6:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


